mail:
  # conf for email sending to amdin
  admin:
    to: ozboxoffice@gmail.com
    from: bluestreamjc@tpg.com.au
    mailer: smtp
    SMTPSecure: tls
    host: smtp.mandrillapp.com
    port: 587
    username: jeangirl186@163.com
    nickname: OzBoxOffice
    password: bHw0jZxX9Kb4QrMqIYY-fg
